baseURL = 'https://PatrickMarques24.github.io/LabVeilTec'
languageCode = 'fr-CH'
title = 'Patrick Marques Meliciano - LabVeilTec'
theme = 'paper'


[menu]

  [[menu.main]]
    identifier = "about"
    name = "À propos"
    url = "/about/"
    weight = 10