baseURL = 'https://example.org/'
languageCode = 'fr-CH'
title = 'Patrick Marques Meliciano - LabVeilTec'
theme = 'hugo-paper'


[menu]

  [[menu.main]]
    identifier = "about"
    name = "À propos"
    url = "/about/"
    weight = 10